### ISSUE TITLE
Add selection for field or simulation mode to login screen

### ISSUE THREAD

**Issue by ShuhaoBai** [GRIDAPPSD/gridappsd-viz#448]
If field mode is selected then Viz will request the field model_id.
Have to logout and log back in to toggle between simulated and field mode or use a
different browser tab.

**Comment by ShuhaoBai** [comment]
If field mode is selected then Viz will request the field model_id.
Have to logout and log back in to toggle between simulated and field mode or use a
different browser tab.

**Comment by ShuhaoBai** [comment]
Built a drop-down menu with FIELD and SIMULATION options in the login pagel. https://github.com/GRIDAPPSD/gridappsd-viz/commit/9f09ba93a0799f2331c42b25b6c6499917d77ed5

**Comment by ShuhaoBai** [comment]
Requirements updated:
Remove the mode selection in the login page as users will have choices to install gridappsd platform either field mode or simulation mode. Plz see https://github.com/GRIDAPPSD/gridappsd-viz/commit/4c428dd5780df6941295db468c3364ac881a3294

**Comment by poorva1209** [comment]
closed. Based on platform response.
